name: Validate HACS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        category:
          - integration
          - plugin
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: ${{ matrix.category }}
          ignore: brands
